<div class="main row-fluid">
    <div class="span8">
        <div class="content-inner">
            <div class="row-fluid">
                <div class="pull-left">
                    <span class="label label-info" style="font-size: 30px; line-height: 47px; padding: 3px 11px; margin-top: -13px;">Buku Tamu</span>
                </div>

            </div>
            
            <br />
            <br />
            
            <?php echo $this->form;  ?>
        </div>
    </div>
    <div class="sidebar span4 well">
        <?php
        echo $this->render('sidebar.phtml');
        ?>
    </div>
</div>