<ul id="myTab" class="nav nav-pills">
    <li class="active">
        <a href="#artikelku" data-toggle="tab">Artikelku</a>
    </li>
    <li class="">
        <a href="#fileku" data-toggle="tab">Fileku</a>
    </li>
    <li class="">
        <a href="#home" data-toggle="tab">Home</a>
    </li>
</ul>


<div class="container">
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="artikelku">
            <h1>Artikelku</h1>
        </div>
        <div class="tab-pane fade" id="fileku">
            <h1>Fileku</h1>
        </div>
        <div class="tab-pane fade" id="home">
            <h1>Home</h1>
        </div>
    </div>
</div>