<div class="row-fluid">
  <h3>Sunting Akun</h3>
</div>
<div class="row-fluid">
  <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
    <div class="row-fluid">
      <div class="pull-left" style="margin-right: 20px">
        <?php echo $this->form->avatar; ?>
      </div>
      <div style="width: 500px">
        <?php echo $this->form->fullname; ?>
        <?php echo $this->form->email; ?>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span8">
        <?php echo $this->form->bio; ?>
      </div>
      <div class="span4">
        <div class="well">
          <p class="f_legend">Ubah Kata Sandi</p>
          <?php echo $this->form->new_password; ?>
          <?php echo $this->form->confirm_password; ?>
        </div>
      </div>
    </div>
    <?php echo $this->form->submit; ?>
  </form>
</div>