<?php $this->headScript()->appendFile($this->baseUrl('lib/jquery-ui/jquery-ui-1.8.23.custom.min.js')); ?>
<div class="row-fluid">
    <h1>Dashboard</h1>
</div>

<div id="widgets" class="row-fluid">
    <div class="span8">
        <div class="w-box" id="w_sort02" style="">
            <div class="w-box-header">
                <i class="icon-book"></i>&nbsp;Buku tamu
                <div class="pull-right">
                    <div class="btn-group">
                        <a class="btn dropdown-toggle btn-mini" data-toggle="dropdown" href="#">
                            <i class="icon-cog"></i> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="w-box-content cnt_a">
                <ul class="unstyled" id="guestbook-list">
                    <?php foreach ($this->guestbooks as $index => $guestbook): ?>
                        <li>
                            <blockquote <?php echo ($index % 2 == 0) ? 'class="pull-right"' : '' ?>>
                                <p><?php echo $guestbook['message']; ?></p>
                                <small>
                                    Dari
                                    <cite title="<?php echo $guestbook['email'] ?>">
                                        <a href="mailto:<?php echo $guestbook['email'] ?>" target="_blank"><?php echo $guestbook['name']; ?> </a>
                                    </cite>
                                    pada <?php echo Date('j M H:i', strtotime($guestbook['created_on'])); ?>
                                </small>
                            </blockquote>

                            <div class="clearfix"></div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="w-box">
            <div class="w-box-header">
                <i class="icon-comments"></i>&nbsp;Komentar Terbaru
            </div>
            <div class="w-box-content cnt_a" id='comment-box-content'>
                <ul class="unstyled" id="comment-list">
                    <?php foreach ($this->latestComments as $index => $comment): ?>
                        <?php
                        $url = $this->url(array(
                            'module'     => 'default',
                            'controller' => 'article',
                            'action'     => 'view',
                            'id'         => $comment['article_id']
                        ));
                        ?>
                        <li>
                            <blockquote>
                                <a href="<?php echo $url; ?>#comment"
                                   class="comment-content"
                                   target='_blank'>
                                       <?php echo $comment['comment_content']; ?>
                                </a>
                                <small>
                                    Oleh
                                    <cite>
                                        <a href="#"><?php echo $comment['username']; ?></a>
                                    </cite>
                                    pada
                                    <b>"<?php echo $comment['article_title']; ?>"</b>
                                    <?php echo $this->timeSince(time() - strtotime($comment['created_on'])); ?>
                                </small>
                            </blockquote>

                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>