<?php
$create = $this->url(array('action' => 'create'));
$control = $this->paginationControl($this->paginator, 'Sliding',
        'partial/pagination_control.phtml');
?>

<div class="row-fluid">
  <h3 style="display: inline">Jajak Pendapat</h3>
  <a href="<?php echo $this->url(array('action' => 'create')); ?>"
    class="btn btn-link label label-success">
   Posting Baru
  </a>
</div>

<div class="row-fluid">
  <div class="span8">
    <form action="" method="post" name="del">
      <div class="row-fluid">
        <div class="span2">
          <button class="btn btn-mini btn-danger" type="submit"
                  name="delete"
                  onclick="if(!confirm(
                    'Apakah anda yakin ingin menghapus polling yang dipilih?'))
                    return false;">
            <i class="icon-trash"></i>
          </button>          
        </div>
        <div class="span5 offset5">
          <?php echo $control; ?>
        </div>
      </div>
      <div class="row-fluid">
        <table class="table table-striped table-condensed"
               id="tb-polling">
          <col width="4%"/>
          <col width="60%"/>
          <col width="10%"/>
          <col width="5%"/>
          <col width="12%"/>
          <thead>
            <tr>
              <th>
                <input type="checkbox"
                       onChange="
                         if($(this).attr('checked'))
                           $('#tb-polling input[type=checkbox]')
                         .attr('checked', true);
                         else 
                           $('#tb-polling input[type=checkbox]')
                         .removeAttr('checked');
                       "/>
              </th>
              <th>Pertanyaan</th>
              <th></th>
              <th>Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>

            <?php foreach ($this->paginator as $index => $polling): ?>
              <?php
              $delete = $this->url(array('action' => 'delete', 'id'
                  => $polling->id));
              $update  = $this->url(array('action'  => 'edit', 'id'
                  => $polling->id));
              $activate = $this->url(array(
                  'action'    => 'activate',
                  'id'        => $polling->id));
              $deactivate = $this->url(array(
                  'action' => 'deactivate',
                  'id'     => $polling->id));
              $view    = $this->url(array(
                  'currentPolling' => $polling->id));
              ?>

              <tr>
                <td><input type="checkbox" name="delete[]"
                           value="<?php echo $polling->id; ?>"
                           id="" /></td>
                <td><?php echo $polling->question; ?></td>
                <td>
                  <?php if ($polling->active == 1): ?>
                    <span class="badge badge-info">Aktif
                      <a href="<?php echo $deactivate; ?>"
                         title="Nonaktifkan">
                        <i class="icon-remove"></i>
                      </a>
                    </span>
                  <?php endif; ?>
                </td>
                <td><?php echo $polling->total; ?></td>
                <td>

                  <a title="Sunting" href="<?php echo $update; ?>">
                    <i class="icon-edit"></i>
                  </a>

                  <a href="<?php echo $view; ?>" 
                     title="Detail" onclick="showDetail">
                    <i class="icon-eye-open"></i>
                  </a>

                  <a title="Hapus" 
                     onclick="if(!confirm('Apakah anda yakin ?'))
                       return false;"
                     href="<?php echo $delete; ?>">
                    <i class="icon-trash"></i>
                  </a>

                  <?php if ($polling->active != 1): ?>
                    <a href="<?php echo $activate; ?>"
                       title="Tandai sebagai polling aktif">
                      <i class="icon-flag"></i>
                    </a>
                  <?php endif; ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </form>
  </div>
  <div class="span4">
    <?php if (isset($this->currentPollingResult)): ?>
      <div class="span12 well">
        <p class="f_legend">
          <?php echo $this->currentPollingResult[0]['question']; ?>
        </p>
        <ul>
          <?php foreach ($this->currentPollingResult as $key => $result): ?>
            <?php
            $percent = strstr($result['percent'], '%', true);
            if ($percent <= 10)
              $class   = 'progress-danger';
            elseif ($percent <= 20)
              $class   = 'progress-warning';
            elseif ($percent <= 30)
              $class   = 'progress-info';
            elseif ($percent > 40)
              $class   = 'progress-success';
            ?>
            <li>
              <?php echo $result['answer']; ?>
              <span class="text-info pull-right">
                <?php echo $result['total']; ?> Vote
              </span>
              <div class="progress <?php echo $class ?>">
                <div class="bar"
                     style="width: <?php echo $result['percent'] ?>">
                  <?php echo round($result['percent']) . '%' ?>
                </div>
              </div>
            </li>
          <?php endforeach; ?>
        </ul>
      </div

    </div>
  <?php endif; ?>
</div>

