<?php
//$auth = Zend_Auth::getInstance();
?>

<div class="main row-fluid">

    <div class="span8">
        <div class="content-inner">
            <div class="row-fluid">
                <div class="pull-left">
                    <span class="label label-info" style="font-size: 30px; line-height: 47px; padding: 3px 11px; margin-top: -13px;">Artikel</span>
                    <?php if ($this->auth->hasIdentity() && $user = $this->auth->getIdentity()): ?>
                    <?php $linkPosting = $this->url(array('controller'=> 'news', 'module'=>'admin', 'action' => 'create')) ?>
                        <a href="<?php echo $linkPosting; ?>" 
                           class="btn btn-link label label-success">Tambah Berita</a>
                    <?php endif; ?>
                </div>
                <div class="pull-right">
                    <?php if (null !== $this->tag): ?>
                        <h5>Artikel dengan tag #<?php echo $this->tag; ?></h5>
                    <?php endif; ?>
                </div>
            </div>

            <br />
            <br />

            <ul class="unstyled article">
                <?php foreach ($this->articles as $index => $article): ?>
                    <?php
                    $link = $this->url(array('controller' => 'article', 'action' => 'view', 'id' => $article['id']));
                    ?>
                    <li>
                        <article>
                            <div class="pull-left">
                                <?php echo $this->thumbnail('avatar', $article['avatar'], 'no-avatar.jpg', 50, 50, 100, ''); ?>
                            </div>
                            <div class="article-content">
                                <h5>
                                    <div class="well well-small" style="min-height:20px; padding: 7px;">
                                        <a style="color: #000;" href="<?php echo $link ?>">
                                            <?php echo $article['title']; ?>
                                        </a>
                                    </div>
                                </h5>
                                <?php echo strip_tags($this->truncate($article['content'], 500, "&nbsp;<a href='{$link}'><span class='label label-info'>more</span></a>", true, true)); ?>
                            </div>
                            <div class="article-footer">
                                <i class="icon-eye-open"></i>&nbsp;<?php echo $article['views']; ?>&nbsp;&nbsp;
                                <i class="icon-comments"></i>&nbsp;<?php echo $article['comments'] ?> &nbsp;&nbsp;
                                <i class="icon-thumbs-up"></i>&nbsp;<?php echo (null !== $article['likes']) ? count(explode(',', $article['likes'])) : 0; ?> &nbsp;&nbsp;
                                <i class="icon-tags"></i>&nbsp;<?php echo $this->tags($article['tags']); ?>&nbsp;&nbsp;
                            </div>
                            <div class="article-footer pull-right">
                                <span class="day"><small>Dibuat pada <span class="day"><?php echo Date('j', strtotime($article['created_on'])); ?></span>
                                        <span class="month"><?php echo Date('M', strtotime($article['created_on'])); ?></span>
                                        oleh&nbsp;<a href="#"><?php echo $article['created_by']; ?></a>&nbsp;&nbsp;
                                    </small>
                            </div>
                        </article>
                        <div class="clearfix"></div>
                        <hr />
                    </li>
                <?php endforeach; ?>
            </ul>
            <br />
            <br />
            <br />

            <?php echo $this->paginationControl($this->articles, 'sliding', 'pagination_control.phtml'); ?>


        </div>
    </div>
    <div class="span4 well sidebar">
        <div class="widget top-blue">
            <div class="widget-header">
                <h4>Tag</h4>
            </div>
            <div class="widget-content">
                <?php echo $this->widget()->getTagCloud(); ?>
            </div>
        </div>
        <?php echo $this->render('sidebar.phtml'); ?>
    </div>
</div>