<!--<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button class="btn btn-navbar" data-toggle="collpase" data-target=".nav collapse" type="button">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="brand">Bootstrap</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Getting Started</a></li>
                    <li><a href="#">Scaffolding</a></li>
                    <li><a href="#">Base CSS</a></li>
                    <li><a href="#">Component</a></li>
                    <li><a href="#">Javascript</a></li>
                    <li><a href="#">Customize</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


Subhead

<header class="jumbotron subhead" id="overview">
    <div class="container">
        <h1>Getting started</h1>
        <p class="lead">
            Overview of the projects, its contents, and how to get started with a simple template
        </p>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix-top">
                <li><a href="#download-bootstrap">
                        <i class="icon-chevron-right"></i>Download
                    </a></li>
                <li><a href="#file-structure">
                        <i class="icon-chevron-right"></i>File Structure
                    </a></li>
                <li><a href="#contents">
                        <i class="icon-chevron-right"></i>Contents
                    </a></li>
                <li><a href="#html-templates">
                        <i class="icon-chevron-right"></i>HTML Templates
                    </a></li>
                <li><a href="examples">
                        <i class="icon-chevron-right"></i>Examples
                    </a></li>
                <li><a href="what-next">
                        <i class="icon-chevron-right"></i>What's Next?
                    </a></li>
            </ul>
        </div>
        <div class="span9">
            <section id="download-bootstrap">
                <div class="page-header">
                    <h1>1. Download</h1>
                </div>
                <p class="lead">
                    Before downloading, be sure to have a code editor (we recommend Sublime Text 2) and some working knowledge of HTML and CSS. We won't walk through the source files here, but they are available for download. We'll focus on getting started with the compiled Bootstrap files.
                </p>
                <div class="row-fluid">
                    <div class="span6">
                        <h2>Download compiled</h2>
                        <p>
                            <strong>Fastest way to get started:</strong> get the compiled and minified versions of our CSS, JS, and images. No docs or original source files.
                        </p>
                        <p>
                            <a href="#" class="btn btn-large btn-primary">Download Bootsrap</a>
                        </p>
                    </div>
                    <div class="span6">
                        <h2>Download source</h2>
                        <p>
                            Get the original files for all CSS and JavaScript, along with a local copy of the docs by downloading the latest version directly from GitHub.
                        </p>
                        <p>
                            <a href="#" class="btn btn-large">Download Bootstrap source</a>
                        </p>
                    </div>
                    
                </div>
            </section>
            <section id="file-structure">
                <div class="page-header">
                    <h1>2.File Structure</h1>
                    
                </div>
                <p class="lead">
                    Within the download you'll find the following file structure and contents, logically grouping common assets and providing both compiled and minified variations.
                </p>
                <p>
                    Within the download you'll find the following file structure and contents, logically grouping common assets and providing both compiled and minified variations.
                </p>
            </section>
            <section id="contents">
                
            </section>
            <section id="html-templates">
                
            </section>
            <section id="examples">
                
            </section>
            <section id="what-next">
                
            </section>
        </div>
    </div>
</div>

=============================================================================================================================================================================================


<div class="container">
    <div class="hero-unit">
        <h1>Hello World</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
        </p>
        <p><a href="#" class="btn btn primary btn-large">Learn It</a></p>

    </div>
    <div class="row">
        <div class="span4">
            <h2>Heading2</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
            </p>
            <p>
                <a href="#" class="btn btn primary btn-large">Learn It</a>
            </p>
        </div>
        <div class="span4">
            <h2>Heading2</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
            </p>
            <p>
                <a href="#" class="btn btn primary btn-large">Learn It</a>
            </p>

        </div>
        <div class="span4">
            <h2>Heading2</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
            </p>
            <p>
                <a href="#" class="btn btn primary btn-large">Learn It</a>
            </p>

        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row-fluid">

    </div>

    <div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
            </ul>
        </div>
    </div>
    <div class="span9">
        <div class="hero-unit">
            <h1>Hello</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
            </p>
            <p>
                <a href="#" class="btn btn primary btn-large">Learn It</a>
            </p>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <h2>Heading2</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
                </p>
                <p>
                    <a href="#" class="btn btn primary btn-large">Learn It</a>
                </p>
            </div>
            <div class="span4">
                <h2>Heading2</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
                </p>
                <p>
                    <a href="#" class="btn btn primary btn-large">Learn It</a>
                </p>
            </div>
            <div class="span4">
                <h2>Heading2</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
                </p>
                <p>
                    <a href="#" class="btn btn primary btn-large">Learn It</a>
                </p>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <h2>Heading2</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
                </p>
                <p>
                    <a href="#" class="btn btn primary btn-large">Learn It</a>
                </p>
            </div>
            <div class="span4">
                <h2>Heading2</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
                </p>
                <p>
                    <a href="#" class="btn btn primary btn-large">Learn It</a>
                </p>
            </div>
            <div class="span4">
                <h2>Heading2</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
                </p>
                <p>
                    <a href="#" class="btn btn primary btn-large">Learn It</a>
                </p>
            </div>
        </div>

    </div>
    <footer>
        <p>Wildan Fath Malik 2012</p>
    </footer>

</div>

<div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
        
    </div>
    
    <a href="#myCarousel" class="left carousel-control" data-slide="prev">‹</a>
    <a href="#myCarousel" class="right carousel-control" data-slide="next">›</a>
    
    
</div>




===================================================================================================================================


<div class="navbar navbar-inverse navbar-fixed-top">

</div>

<header class="jumbotron subhead" id="overview">
    <div class="container">
        <h1>
            Getting Started!!!
        </h1>
        <p class="lead">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
        </p>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix-top">
                <li class="active"><a href="#download-bootstrap">
                        Download
                        <i class="icon-chevron-right"></i>
                    </a>
                </li>
                <li class="">
                    <a href="file-structure">
                        File Structure
                        <i class="icon-chevron-right"></i>
                    </a>
                </li>
                <li class="">

                    <a href="contents">
                        Contents
                        <i class="icon-chevron-right"></i>
                    </a>
                </li>
                <li class="">

                    <a href="html-template">
                        HTML Template
                        <i class="icon-chevron-right"></i>
                    </a>
                </li>
                <li class="">

                    <a href="examples">
                        Examples
                        <i class="icon-chevron-right"></i>
                    </a>
                </li>
                <li class="">

                    <a href="what-next">
                        What's Next?
                        <i class="icon-chevron-right"></i>
                    </a>
                </li>
            </ul>

        </div>
        <div class="span9">

            <section id="download-bootsrap">
                <div class="page-header">
                    <h1>1. Download</h1>
                </div>
                <p class="lead">
                    Before downloading, be sure to have a code editor (we recommend <a href="http://sublimetext.com/2">Sublime Text 2</a>) and some working knowledge of HTML and CSS. We won't walk through the source files here, but they are available for download. We'll focus on getting started with the compiled Bootstrap files.
                </p>

                <div class="row-fluid">
                    <div class="span6">
                        <h2>Download Compiled</h2>
                        <p>
                            <strong>Fastest way to get started:</strong> get the compiled and minified versions of our CSS, JS, and images. No docs or original source files.
                        </p>
                        <p>
                            <a href="#" class="btn btn-primary btn-large">Download Bootstrap</a>
                        </p>
                    </div>
                    <div class="span6">
                        <h2>Download Source</h2>
                        <p>
                            Get the original files for all CSS and JavaScript, along with a local copy of the docs by downloading the latest version directly from GitHub.
                        </p>

                        <p>
                            <a href="#" class="btn btn-large">Download Source</a>
                        </p>
                    </div>
                </div>
            </section>

            <section id="file-structure">
                <div class="page-header">
                    <h1>2. File Structure</h1>
                </div>
                <p class="lead">
                    Within the download you'll find the following file structure and contents, logically grouping common assets and providing both compiled and minified variations.
                </p>
                <p>
                    Once downloaded, unzip the compressed folder to see the structure of (the compiled) Bootstrap. You'll see something like this:
                </p>
                <pre class="prettyprint">
                    bootstrap/
                    ├── css/
                    │   ├── bootstrap.css
                    │   ├── bootstrap.min.css
                    ├── js/
                    │   ├── bootstrap.js
                    │   ├── bootstrap.min.js
                    └── img/
                        ├── glyphicons-halflings.png
                        └── glyphicons-halflings-white.png
                </pre>
                <p>
                    This is the most basic form of Bootstrap: compiled files for quick drop-in usage in nearly any web project. We provide compiled CSS and JS (<code>bootstrap.*</code>), as well as compiled and minified CSS and JS (<code>bootstrap.min.*</code>). The image files are compressed using <a href="http://imageoptim.com/">ImageOptim</a>, a Mac app for compressing PNGs.
                </p>
                <p>
                    Please note that all JavaScript plugins require jQuery to be included.
                </p>
            </section>

            <section id="contents">
                <div class="page-header">
                    <h1>What's included?</h1>
                    <p class="lead">
                        Bootstrap comes equipped with HTML, CSS, and JS for all sorts of things, but they can be summarized with a handful of categories visible at the top of the <a href="getbootstrap.com">Bootstrap documentation</a>.
                    </p>
                    <h2>Docs Section</h2>
                    <h4><a href="#">Scaffolding</a></h4>
                    <p>
                        Global styles for the body to reset type and background, link styles, grid system, and two simple layouts.
                    </p>
                    <h4><a href="#">Base CSS</a></h4>
                    <p>
                        Styles for common HTML elements like typography, code, tables, forms, and buttons. Also includes <a href="#">Glyphicons</a>, a great little icon set.
                    </p>
                    <h4><a href="#">Components</a></h4>
                    <p>
                        Styles for common HTML elements like typography, code, tables, forms, and buttons. Also includes Glyphicons, a great little icon set.
                    </p>
                    <h4><a href="#">JavaScript Plugins</a></h4>
                    <p>
                        Similar to Components, these JavaScript plugins are interactive components for things like tooltips, popovers, modals, and more.
                    </p>

                    <h2>List of Components</h2>
                    <p>
                        Together, the <strong>Components</strong> and <strong>JavaScript</strong> plugins sections provide the following interface elements:
                    </p>
                    <ul>
                        <li>Button</li>
                        <li>Nuf</li>
                        <li>Fun</li>
                        <li>1cak</li>
                    </ul>
                </div>
            </section>

            <section id="html-template">
                <div class="page-header">
                    <h1>4. Basic HTML Template</h1>
                    <p class="lead">
                        With a brief intro into the contents out of the way, we can focus on putting Bootstrap to use. To do that, we'll utilize a basic HTML template that includes everything we mentioned in the <a href="#">File structure.</a>
                    </p>
                    <p>
                        Now, here's a look at a typical <strong>HTML</strong> file:
                    </p>
                    <pre class="prettyprint linenums">
                        <ol class="linenums">
                            <li class="L1"></li>
                            <li class="L2"></li>
                            <li class="L3"></li>
                            <li class="L4"></li>
                            <li class="L5"></li>
                            <li class="L6"> </li>
                        </ol>
                    </pre>

                </div>
            </section>

        </div>
    </div>
</div>

<footer>

</footer>


=======================================================================================================================

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button class="btn btn-navbar" type="button" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="brand">KASKUS</a>
            
        </div>
    </div>
</div>

<ul id="myTab" class="nav nav-tabs">
    <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
    <li class=""><a href="#profile" data-toggle="tab">Profile</a></li>
    <li class=""><a href="#about" data-toggle="tab">About</a></li>'
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Dropdown<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="#dropdown1" data-toggle="tab">New</a></li>
            <li><a href="#dropdown2" data-toggle="tab">Old</a></li>
        </ul>
    </li>
</ul>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="home">
        <p>
            Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.
        </p>
    </div>
    <div class="tab-pane fade" id="profile">
        <p>
            Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
        </p>
    </div>
    <div class="tab-pane fade" id="about"
         <p>
            Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
        </p>
    </div>
    <div class="tab-pane fade" id="dropdown1">
        <p>
            Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.
        </p>
    </div>
    <div class="tab-pane fade" id="dropdown2">
        Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.
    </div>
</div>-->


<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="brand">Bootsrap</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li class=""><a href="#">Home</a></li>
                    <li class=""><a href="#">Home</a></li>
                    <li class=""><a href="#">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<header class="jumbotron subhead" id="overview">
    <div class="container">
        <h1>Base CSS</h1>
        <p class="lead">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
        </p>

        
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="span3">
            <ul class="nav nav-list bs-docs-sidenav">
                <li class=""><a href="#"><i class="icon-chevron-right"></i>Home</a></li>
                <li class=""><a href="#"><i class="icon-chevron-right"></i>Judge</a></li>
                <li class=""><a href="#"><i class="icon-chevron-right"></i>Where</a></li>
            </ul>
        </div>
        <div class="span9">
            
        </div>
    </div>
</div>