        
<div class="main row-fluid">
    <div class="span8">
        <div id="highlight" class="carousel slide">
            <div class="carousel-inner">
                <div class="active item">
                    <img src="/../upload/highlight/angklung.jpeg" alt="" />
                </div>
                <div class="item"><img src="/../upload/highlight/smkn4bdg.jpg" alt="" /></div>
            </div>

            <a href="#highlight" class="carousel-control left" data-slide="prev">&lsaquo;</a>
            <a href="#highlight" class="carousel-control right" data-slide="next">&rsaquo;</a>
        </div>
    </div>
    <div class="post span4 top-green" style="">
        <div class="inner">
            <h4>Berita Terbaru</h4>
            <ul class="news-list">
                <li><a href="#">Festival Paduan Angklung ITB XII</a></li>
                <li><a href="#">Study Tour TIK SMKN 4 Bandung</a></li>
                <li><a href="#">Pengembangan Sistem Informasi Terintegrasi</a></li>
                <li><a href="#">Renovasi ulang gedung sekolah</a></li>
                <li><a href="#">Tutorial dan pengenalan Zend Framework</a></li>
                <li><a href="#">Masjid SMK Negeri 4 Bandung Belum siap dipakai</a></li>
                <li><a href="#">Siswa mengeluhkan tidak adanya air untuk wudhu</a></li>
                <li><a href="#">Suasana pada saat siswa disibukan Tugas Akhir</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="jurusan row-fluid">
    <div class="inner">
        <div class="span4">
            <i class="icon-desktop icon-2x"></i>
            <h3>Teknik Informatika</h3>
            <p>Rekayasa Perangkat Lunak, Teknik Komputer dan Jaringan, dan Multimedia.</p>
        </div>
        <div class="span4">
            <i class="icon-bolt icon-2x" style="margin-left: 10px;"></i>
            <h3>Ketenaga Listrikan</h3>
            <p>Teknik Instalasi Tenaga Listrik, dan Teknik Otomasi Industri.</p>
        </div>
        <div class="span4">
            <i class="icon-facetime-video icon-2x"></i>
            <h3>Audio Video</h3>
            <p>Teknik yang bekerja di bidang elektronika khususnya Audio dan Video.</p>
        </div>
    </div>
</div>
<div class="row-fluid row-fluid-bordered">
    <div class="content-inner">
        <div class="span3">
            <h4><i class="icon-picture"></i> Galeri</h4>
            <p>Pelatihan teknis website Lamanbudaya di hotel Gren Alia Cikini.
                <a href="javascript:void(0)" id="control-left"><i class="icon-chevron-left" ></i></a>
                <a href="javascript:void(0)" id="control-right"><i class="icon-chevron-right" ></i></a>
            </p>

        </div>
        <div class="span9">
            <div class="jcarousel">
                <ul>
                    <li><img class="thumbnail" src="<?php echo $this->baseUrl('timthumb.php?src=upload/gallery/foto1.jpg&w=320&h=260&q=100'); ?>" alt="" /></li>
                    <li><img class="thumbnail" src="<?php echo $this->baseUrl('timthumb.php?src=upload/gallery/foto2.jpg&w=320&h=260&q=100'); ?>" alt="" /></li>
                    <li><img class="thumbnail" src="<?php echo $this->baseUrl('timthumb.php?src=upload/gallery/foto3.jpg&w=320&h=260&q=100'); ?>" alt="" /></li>
                    <li><img class="thumbnail" src="<?php echo $this->baseUrl('timthumb.php?src=upload/gallery/foto3.jpg&w=320&h=260&q=100'); ?>" alt="" /></li>
                    <li><img class="thumbnail" src="<?php echo $this->baseUrl('timthumb.php?src=upload/gallery/foto2.jpg&w=320&h=260&q=100'); ?>" alt="" /></li>
                    <li><img class="thumbnail" src="<?php echo $this->baseUrl('timthumb.php?src=upload/gallery/foto1.jpg&w=320&h=260&q=100'); ?>" alt="" /></li>
                </ul>
            </div>
        </div>
    </div>

</div>
<div class="main row-fluid">
    <div class="span8">
        <div class="content-inner">
            <h4><i class="icon-pushpin"></i> Artikel</h4>
            <ul class="unstyled article">
                <li>
                    <article>
                        <div class="pull-left">
                            <img src="/../upload/avatar/asdf.jpg" alt="" width="50" height="50"/>
                            <div class="date">
                                <span class="day">29</span>
                                <span class="month">Des</span>
                            </div>
                        </div>
                        <div class="article-content">
                            <h5><a href="#">Tutorial membuat halaman login berbasis PHP dan MYSql</a></h5>
                            <p>
                                Lorem ipsum dolor sit amet,aliquip ex ea commodo consequat. cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                        <div class="article-footer">
                            <i class="icon-user"></i> <a href="#">Egi Soleh Hasdi</a>&nbsp;&nbsp;
                            <i class="icon-eye-open"></i> 1012 &nbsp;&nbsp;
                            <i class="icon-comments"></i> 192 &nbsp;&nbsp;
                            <i class="icon-thumbs-up"></i> 50 &nbsp;&nbsp;
                            <i class="icon-tags"></i> <a href="#">MySQL</a>, <a href="#">PHP</a>&nbsp;&nbsp;
                        </div>
                    </article>
                    <hr />
                </li>
                <li>
                    <article>
                        <div class="pull-left">
                            <img src="/../upload/avatar/asdf.jpg" alt="" width="50" height="50"/>
                            <div class="date">
                                <span class="day">29</span>
                                <span class="month">Des</span>
                            </div>
                        </div>
                        <div class="article-content">
                            <h5><a href="#">Tutorial membuat halaman login berbasis PHP dan MYSql</a></h5>
                            <p>
                                Lorem ipsum dolor sit amet,aliquip ex ea commodo consequat. cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                        <div class="article-footer">
                            <i class="icon-user"></i> <a href="#">Egi Soleh Hasdi</a>&nbsp;&nbsp;
                            <i class="icon-eye-open"></i> 1012 &nbsp;&nbsp;
                            <i class="icon-comments"></i> 192 &nbsp;&nbsp;
                            <i class="icon-thumbs-up"></i> 50 &nbsp;&nbsp;
                            <i class="icon-tags"></i> <a href="#">MySQL</a>, <a href="#">PHP</a>&nbsp;&nbsp;
                        </div>
                    </article>
                    <hr />
                </li>
                <li>
                    <article>
                        <div class="pull-left">
                            <img src="/../upload/avatar/asdf.jpg" alt="" width="50" height="50"/>
                            <div class="date">
                                <span class="day">29</span>
                                <span class="month">Des</span>
                            </div>
                        </div>
                        <div class="article-content">
                            <h5><a href="#">Tutorial membuat halaman login berbasis PHP dan MYSql</a></h5>
                            <p>
                                Lorem ipsum dolor sit amet,aliquip ex ea commodo consequat. cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                        <div class="article-footer">
                            <i class="icon-user"></i> <a href="#">Egi Soleh Hasdi</a>&nbsp;&nbsp;
                            <i class="icon-eye-open"></i> 1012 &nbsp;&nbsp;
                            <i class="icon-comments"></i> 192 &nbsp;&nbsp;
                            <i class="icon-thumbs-up"></i> 50 &nbsp;&nbsp;
                            <i class="icon-tags"></i> <a href="#">MySQL</a>, <a href="#">PHP</a>&nbsp;&nbsp;
                        </div>
                    </article>
                </li>
            </ul>
            <br />
            <br />
            <br />

            <h4><i class="icon-rss"></i>&nbsp; Rubrik Edukasi</h4>
            <ul class="unstyled">
                <?php $feed = Zend_Feed_Reader::import('http://www.kompas.com/getrss/edukasi'); ?>
                <?php foreach ($feed as $index => $news): ?>
                    <?php if ($index < 5): ?>
                        <li>
                            <h5>
                                <a href="<?php echo $news->getLink(); ?>" target="_blank">
                                    <?php echo $news->getTitle(); ?>
                                </a>
                            </h5>
                            <?php echo $news->getDescription(); ?>
                            <div class="clearfix"></div>
                            <?php if ($index != 4): ?>
                                <hr />
                            <?php endif; ?>
                        </li>
                    <?php else: ?>
                        <!--we only display 5 latest news-->
                    <?php endif; ?>

                <?php endforeach; ?>
            </ul>
            <br />
            <br />
            <br />
        </div>
    </div>
    <div class="sidebar span4 well">
        <?php
                echo $this->render('sidebar.phtml');
                ?>
    </div>
</div>