<div class="main row-fluid">
    <div class="span8">
        <div id="highlight" class="carousel slide">
            <div class="carousel-inner">
                <?php
                foreach ($this->sortedHighlight as $index => $highlight) {
                    $imgPath = UPLOAD_FOLDER . 'highlight/' . $highlight['image'];
                    if (file_exists($imgPath)) {
                        $options = 'src=upload/highlight/' . $highlight['image'] . '&w=700&h=300&q=100';
                        $timthumb = $this->baseUrl('timthumb.php?' . $options);
                        $item = "<div class='item" . (($index == 0) ? " active" : "") . "'>";
                        $item .= "<img src='" . $timthumb . "' alt='" . $highlight['title'] . "' />";
                        $item .= "<div class='carousel-caption'>";
                        $item .= "<h4>";
                        if (null !== $highlight['link']) {
                            $item .= "<a href=" . $highlight['link'] . ">" . $highlight['title'] . "</a>";
                        } else {
                            $item .= $highlight['title'];
                        }
                        $item .= "</h4>";
                        $item .="</div>";
                        $item .= "</div>";
                        echo $item;
                    }
                }
                ?>
            </div>

            <a href="#highlight" class="carousel-control left" data-slide="prev">&lsaquo;</a>
            <a href="#highlight" class="carousel-control right" data-slide="next">&rsaquo;</a>
        </div>
    </div>
    <div class="post span4 top-green" style="">
        <div class="inner">
            <h4>Berita Terbaru</h4>
            <ul class="news-list">
                <?php
//                foreach ($this->news as $news) {
//                    echo '<li><a href="#">'.$news['title'].'</a></li>';
//                }
                ?>

                <?php foreach ($this->news as $news): ?>
                    <li><a href="#"><?php echo $news['title']; ?></a></li>
                <?php endforeach; ?>

                <!--                <li><a href="#">Festival Paduan Angklung ITB XII</a></li>
                                <li><a href="#">Study Tour TIK SMKN 4 Bandung</a></li>
                                <li><a href="#">Pengembangan Sistem Informasi Terintegrasi</a></li>
                                <li><a href="#">Renovasi ulang gedung sekolah</a></li>
                                <li><a href="#">Tutorial dan pengenalan Zend Framework</a></li>
                                <li><a href="#">Masjid SMK Negeri 4 Bandung Belum siap dipakai</a></li>
                                <li><a href="#">Siswa mengeluhkan tidak adanya air untuk wudhu</a></li>
                                <li><a href="#">Suasana pada saat siswa disibukan Tugas Akhir</a></li>-->
            </ul>
        </div>
    </div>
</div>
<div class="jurusan row-fluid">
    <div class="inner">
        <div class="span4">
            <i class="icon-desktop icon-2x"></i>
            <h3>Teknik Informatika</h3>
            <p>Rekayasa Perangkat Lunak, Teknik Komputer dan Jaringan, dan Multimedia.</p>
        </div>
        <div class="span4">
            <i class="icon-bolt icon-2x" style="margin-left: 10px;"></i>
            <h3>Ketenaga Listrikan</h3>
            <p>Teknik Instalasi Tenaga Listrik, dan Teknik Otomasi Industri.</p>
        </div>
        <div class="span4">
            <i class="icon-facetime-video icon-2x"></i>
            <h3>Audio Video</h3>
            <p>Teknik yang bekerja di bidang elektronika khususnya Audio dan Video.</p>
        </div>
    </div>
</div>
<div class="row-fluid row-fluid-bordered">
    <?php if (null !== $this->latestAlbumWithPhotos): ?>
        <div class="content-inner">
            <div class="span3">
                <h4><i class="icon-picture"></i> Galeri</h4>
                <p><?php echo $this->latestAlbumWithPhotos['title']; ?></p>
                <a href="javascript:void(0)" id="control-left"><i class="icon-chevron-left" ></i></a>
                <a href="javascript:void(0)" id="control-right"><i class="icon-chevron-right" ></i></a>

            </div>
            <div class="span9">
                <div class="jcarousel">
                    <ul>
                        <?php foreach ($this->latestAlbumWithPhotos['photos'] as $index => $photo): ?>
                            <li><img src="<?php echo $this->baseUrl('timthumb.php?src=' . $photo . '&w=320&h=260&q=100'); ?>; ?>" alt="" /></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
<div class="main row-fluid">
    <div class="span8">
        <div class="content-inner">
            <div class="row-fluid">
                <div class="pull-left">
                    <h4><i class="icon-pushpin"></i> Artikel</h4>
                </div>
                <div class="pull-right">
                    <!--<a href="#">Lihat Semua Artikel</a>-->
                </div>
            </div>
            <ul class="unstyled article">
                <?php foreach ($this->latestArticles as $index => $article): ?>
                    <?php
                    $link = $this->url(array('controller' => 'article', 'action' => 'view', 'id' => $article['id']));
                    ?>
                    <li>
                        <article>
                            <div class="pull-left">
                                <?php echo $this->thumbnail('avatar', $article['avatar'], 'no-avatar.jpg', 50, 50, 100, ''); ?>
                                <div class="date">
                                    <span class="day"><?php echo Date('j', strtotime($article['created_on'])); ?></span>
                                    <span class="month"><?php echo Date('M', strtotime($article['created_on'])); ?></span>
                                </div>
                            </div>
                            <div class="article-content">
                                <h5>
                                    <a href="<?php echo $link ?>">
                                        <?php echo $article['title']; ?>
                                    </a>
                                </h5>
                                <?php echo $this->truncate($article['content'], 250, "&nbsp;<a href='{$link}'>[...]</a>", true, true); ?>
                            </div>
                            <div class="article-footer">
                                <i class="icon-user"></i>&nbsp;<a href="#"><?php echo $article['created_by']; ?></a>&nbsp;&nbsp;
                                <i class="icon-eye-open"></i>&nbsp;<?php echo $article['views']; ?>&nbsp;&nbsp;
                                <i class="icon-comments"></i>&nbsp;<?php echo rand(0, 1000); ?> &nbsp;&nbsp;
                                <i class="icon-thumbs-up"></i>&nbsp;<?php echo $article['likes']; ?> &nbsp;&nbsp;
                                <i class="icon-tags"></i>&nbsp;<?php echo $this->tags($article['tags']); ?>&nbsp;&nbsp;
                            </div>
                        </article>
                        <div class="clearfix"></div>
                        <hr />
                    </li>
                <?php endforeach; ?>
            </ul>
            <br />
            <br />
            <br />

            <h4><i class="icon-rss"></i>&nbsp; Rubrik Edukasi</h4>
            <ul class="unstyled">
                <?php foreach ($this->feeds as $index => $news): ?>
                    <?php if ($index < 5): ?>
                        <li>
                            <h5>
                                <a href="<?php echo $news['link']; ?>" target="_blank">
                                    <?php echo $news['title']; ?>
                                </a>
                            </h5>
                            <?php echo $news['description']; ?>
                            <div class="clearfix"></div>
                            <?php if ($index != 4): ?>
                                <hr />
                            <?php endif; ?>
                        </li>
                    <?php else: ?>
                        <!--we only display 5 latest news-->
                    <?php endif; ?>

                <?php endforeach; ?>
            </ul>
            <br />
            <br />
            <br />
        </div>
    </div>
    <div class="sidebar span4 well">
        <?php
        echo $this->render('sidebar.phtml');
        ?>
    </div>
</div>
