<div class="main row-fluid">

    <div class="span8">
        <div class="content-inner">
            <div class="row-fluid">
                <div class="pull-left">
                    <span class="label label-info" style="font-size: 30px; line-height: 47px; padding: 3px 11px; margin-top: -13px;">Berita</span>
                </div>
            </div>

            <br />
            <br />


            <ul class="unstyled article">
                <?php foreach ($this->newss as $index => $news): ?>
                    <li>
                        <article>
                            <div class="pull-left">


                                <div class="date" style="margin-top: 0px">
                                    <span class="day"><?php echo Date('j', strtotime($news['created_on'])); ?></span>
                                    <span class="month"><?php echo Date('M', strtotime($news['created_on'])); ?></span>
                                    <span class="years"><?php echo Date('Y', strtotime($news['created_on'])); ?></span>
                                </div>

                            </div>
                            <div class="article-content">
                                <h5>
                                    <div class="well well-small" style="min-height:20px; padding: 7px;">
                                        <a style="color: #000;" href="#">
                                            <?php echo $news['title']; ?>
                                        </a>
                                    </div>
                                </h5>

                                <?php echo strip_tags($this->truncate($news['content'], 300, "&nbsp;...", true, true)); ?>

                            </div>

                            <div class="article-footer" style="padding-top: 11px">
                                <i class="icon-eye-open"></i>&nbsp;<?php // echo $article['views'];      ?>&nbsp;&nbsp;
                                <i class="icon-comments"></i>&nbsp;<?php // echo rand(0, 1000);      ?> &nbsp;&nbsp;
                                <i class="icon-thumbs-up"></i>&nbsp;<?php // echo $article['likes'];      ?> &nbsp;&nbsp;
                                <i class="icon-tags"></i>&nbsp;<?php // echo $this->tags($article['tags']);      ?>&nbsp;&nbsp;
                            </div>



                            <div class="article-footer pull-right">
                                <small>
                                    by&nbsp;<a href="#"><?php echo $news['created_by']; ?></a>&nbsp;&nbsp;
                                </small>
                            </div>

                        </article>
                        <div class="clearfix"></div>
                        <hr />
                    </li>
                <?php endforeach; ?>
            </ul>






        </div>
    </div>

    <div class="span4 well sidebar">

        <?php echo $this->render('sidebar.phtml'); ?>

    </div>

</div>