<?php
$this->MinifyHeadLink()
        ->appendStylesheet($this->baseUrl('css/application/news/view.css'));
$this->minifyHeadLink()
        ->appendStylesheet($this->baseUrl('css/application/article/view.css'));
$auth = Zend_Auth::getInstance();
?>


<?php
$permaLink = $this->url(array(
    'controller' => 'news',
    'action' => 'view',
    'module' => 'default',
    'id' => $this->news['id']));


$tweet = "https://twitter.com/intent/tweet?source=webclient&text={$permaLink}";
?>


<div class="main row-fluid">

    <div class="span8">
        <div class="content-inner" style="margin-top: 2px;">

            <ul class="unstyled">

                <li>
                    <ul class="inline pull-right">
                        <li >
                            <a href="#" title="Bagikan di Facebook">fb</a>
                        </li>
                        <li>


                            <a id="shareTwitter" href="<?php echo $tweet ?>">Share Twitter</a>

                        </li>

                    </ul>
                    <div class="clearfix"></div>
                </li>
                <li>

                    <h2 class="">
                        <?php echo $this->news['title'] ?>
                    </h2>
                </li>
                <li>

                    <cite>Diposting oleh : <a href="#"><b><?php echo $this->news['created_by']; ?></b></a>
                        <br />
                        <div><?php echo Date('F j, Y', strtotime($this->news['created_on'])); ?></div>
                    </cite>

                </li>

            </ul>




            <hr class="line-heading"/>

            <?php echo $this->news['content'] ?>

            <iframe src="http://www.facebook.com/plugins/like.php?href=http://local.smkn4bdg.sch.id/news/view/id/8"
                    scrolling="no" frameborder="0"
                    style="border:none; width:450px; height:80px">
            
            </iframe>
            <div class="clearfix"></div>

            <ul class="unstyled inline well" style="border-radius: 0;padding: 5px;">

                <li>
                    <i class="icon-thumbs-up"></i>
                </li>
                <li>
                    <i class="icon-thumbs-up"></i>
                </li>
                <li>
                    <i class="icon-thumbs-up"></i>
                </li>
                <li>
                    <i class="icon-thumbs-up"></i>
                </li>

            </ul>



            <?php if ($this->auth->hasIdentity() && $user = $this->auth->getIdentity()): ?>
                <form action="<?php echo $this->url(); ?>#comment" method="post" id="comment-form">
                    <div class="input-prepend">
                        <div class="add-on">
                            <?php
                            echo $this->thumbnail('avatar', $user->avatar, 'no-avatar.jpg'
                                    , 50, 50, 100, '');
                            ?>
                            <?php echo $this->form->submit; ?>
                        </div>
                        <?php echo $this->form->content; ?>
                    </div>
                </form>
            <?php else: ?>
                <?php
                $loginUrl = $this->url(array(
                    'controller' => 'user',
                    'action' => 'login',
                    'module' => 'admin',
                    'return' => "news|view|id|{$this->news['id']}#comment"), null, true);
                ?>
                <div class="alert">
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                    Anda harus <a href="<?php echo $loginUrl ?>">
                        Login</a> untuk memberikan komentar.
                </div>
            <?php endif; ?>





        </div>

    </div>

    <div class="span4 sidebar well">
        <?php echo $this->render('sidebar.phtml'); ?>
    </div>
</div>

<script>


    $('#shareTwitter').click(function(event){
        event.preventDefault();
        
        var w = 700;
        var h = 500;
        var x = screen.width/2 - w/2;
        var y = screen.height/2 - h/2;
        
        window.open($(this).attr('href'),'1362073567533','width='+w+',height='+h+',toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left='+x+',top='+y+'');return false;
    })

    
    


</script>