<?php echo $this->flashMessenger($this->messages); ?>
<div class="row-fluid">
  <h3 style="display: inline">Lowongan Kerja</h3>
  <a href="<?php echo $this->url(array('action' => 'create')); ?>"
     class="btn btn-link label label-success">Posting Baru</a>
</div>
<div class="row-fluid">
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th><input type="checkbox" name="" id="" /></th>
        <th>Judul</th>
        <th>Tags</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->jobs as $index => $job): ?>
        <tr>
          <td><input type="checkbox" /></td>
          <td><?php echo $job->title; ?></td>
          <td><?php echo $this->tags($job->tags); ?></td>
          <td>
            <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $job->id)); ?>">
              <i class="icon-edit"></i>
            </a>
            <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $job->id)); ?>">
              <i class="icon-trash"></i>
            </a>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>