<form action="" method="post" autocomplete="off" class="form form-horizontal well">
  <fieldset>
    <legend class="f_legend">Informasi Akun</legend>
    <?php echo $this->form->username; ?>
    <?php echo $this->form->password; ?>
    <?php echo $this->form->confirm_password; ?>
    <?php echo $this->form->role; ?>
    <div class="form-actions">
      <?php echo $this->form->submit; ?>
    </div>
  </fieldset>
</form>