<?php echo $this->flashMessenger($this->messages); ?>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>Nama User</th>
      <th>Nama Lengkap</th>
      <th>Email</th>
      <th>Role</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->users as $index => $user): ?>
      <tr>
        <td>
          <?php echo $this->thumbnail('avatar', $user->avatar, 'no-avatar.jpg', 32, 32); ?>
        </td>
        <td><?php echo $user->username; ?></td>
        <td><?php echo $user->fullname; ?></td>
        <td><?php echo $user->email; ?></td>
        <td><?php echo $user->role; ?></td>
        <td>
          <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $user->username)); ?>"
             title="Sunting">
            <i class="icon-edit"></i>
          </a>
          <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $user->username)); ?>">
            <i class="icon-trash"></i>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>