<?php $this->headScript()->appendFile($this->baseUrl('lib/plupload/js/plupload.full.js')) ?>
<?php $this->headScript()->appendFile($this->baseUrl('lib/plupload/js/jquery.plupload.queue/jquery.plupload.queue.full.js')) ?>
<?php $this->headScript()->appendFile($this->baseUrl('lib/plupload/js/i18n/id.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/gallery/manage.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/gallery/manage.css')); ?>
<?php echo $this->flashMessenger($this->messages); ?>
<form action="" method="post">
  <div class="row-fluid" style="margin-bottom: 25px">
    <div class="pull-left">
      <h3>Sunting Album <strong>(<?php echo $this->album['title']; ?>)</strong></h3>
    </div>
  </div>
  <div class="row-fluid">
    <div class="pull-left">
      <button name="action"
              value="delete"
              class="btn btn-mini btn-danger"
              onclick="return confirm('Apakah anda yakin ingin menghapus foto yang dipilih?')">
        <i class="icon-trash"></i>
      </button>
    </div>
    <div class="pull-right">
      <?php echo $this->paginationControl($this->album['photos'], 'sliding', 'partial/pagination_control.phtml'); ?>
    </div>
  </div>
  <hr />
  <div class="row-fluid">
    <ul class="thumbnails" id="photos">
      <?php foreach ($this->album['photos'] as $index => $photo): ?>
        <li>
          <label for="<?php echo $photo['id']; ?>">
            <input type="checkbox" 
                   name="photos[]" 
                   id="<?php echo $photo['id'] ?>"
                   value="<?php echo $photo['id']; ?>" 
                   style=""/>
            <img src="<?php echo $photo['src']; ?>" alt=""  class="thumbnail"/>
          </label>
        </li>
      <?php endforeach; ?>
    </ul>
  </div>
  <hr />
  <div class="row-fluid">
    <div id="photo_upload">

    </div>
  </div>
</form>