<?php echo $this->flashMessenger($this->messages); ?>
<div class="row-fluid" style="margin-bottom: 20px">
  <h3 style="display: inline">Artikel</h3>
  <a href="<?php echo $this->url(['action' => 'create']); ?>"
     class="btn btn-link label label-success">
    Posting Artikel
  </a>
</div>

<form action="" method="post">

  <div class="row-fluid">
    <div class="row-fluid">
      <div class="pull-left">
        <button class="btn btn-mini"
                name="action"
                value="delete"
                onclick="if(!confirm('Apakah anda yakin ingin menghapus semua artikel '
                    +'yang dipilih?')) return false;">
          <i class="icon-trash"></i>
        </button>

        <button class="btn btn-mini" name="action" value="filter">
          <i class="icon-filter"></i>
          Gunakan Filter
        </button>
        <button class="btn btn-mini">
          Atur Ulang Filter
        </button>
      </div>
      <div class="pull-right">
        <?php echo $this->paginationControl($this->articles, 'sliding', 'partial/pagination_control.phtml'); ?>
      </div>

    </div>
    <div class="row-fluid">
      <table class="table table-striped table-condensed" id="article-table">
        <thead>
          <tr>
            <th>
              <input type="checkbox" 
                     onchange="
                       var checkboxes = $('#article-table tbody input:checkbox');
                       if($(this).attr('checked')) {
                         $(checkboxes).attr('checked', true);
                       } else {
                         $(checkboxes).removeAttr('checked');
                       }"/>
            </th>
            <th>Judul</th>
            <th>Status</th>
            <th><i class="icon-tags"></i></th>
            <th><i class="icon-eye-open"></i></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->articles as $index => $article): ?>
            <tr>
              <td>
                <input type="checkbox" name="articles[]"
                       value="<?php echo $article->id; ?>"/>
              </td>
              <td>
                <a href="#" target="_blank">
                  <strong><?php echo $article->title; ?></strong>
                </a>
              </td>
              <td><?php echo $this->status($article->status); ?></td>
              <td><?php echo $this->tags($article->tags); ?></td>
              <td><span class="badge badge-info"><?php echo $article->views; ?></span></td>
              <td>
                <a href="<?php echo $this->url(['action' => 'edit', 'id' => $article->id]); ?>">
                  <i class="icon-edit"></i>
                </a>
                <a href="<?php echo $this->url(['action' => 'delete', 'id' => $article->id]); ?>"
                   onclick="if(!confirm('Apakah anda yakin ingin menghapus artikel'+
                         ' ini?.')) return false">
                  <i class="icon-trash"></i>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>

</form>