<?php
$key = "AIzaSyCTNj8ia2gmUviCAL5Beyrip_OQSI_hJdw";
$sensor = "false";
$libraries = "places";

$this->MinifyHeadScript()
        ->prependFile("https://maps.googleapis.com/maps/api/js?key={$key}&sensor={$sensor}&libraries={$libraries}")
        ->prependFile($this->baseUrl('lib/jquery-ui/jquery-ui-1.8.23.custom.min.js'))
        ->appendFile($this->baseUrl('lib/multiselect/jquery.multiselect.js'))
        ->appendFile($this->baseUrl('js/prakerin.js'));

$this->headLink()
//        ->prependStylesheet($this->baseUrl('lib/jquery-ui/css/smoothness/jquery-ui-1.8.20.custom.css'))
        ->appendStylesheet($this->baseUrl('lib/multiselect/jquery.multiselect.css'));
?>

<div class="row-fluid">
  <form action="" method="post" class="form" id="prakerin-form">
    <div class="row-fluid">
      <div class="span8">
        <div class="input-append well">
          <input type="text" id="search-input" class="span11"
                 placeholder="Cari Perusahaan, Misal: PT Inti Bandung" />
          <div class="add-on">
            <i class="icon-map-marker"></i>
          </div>
        </div>
        <div class="well">
          <div id="map-canvas"></div>
        </div>
      </div>

      <div class="span4 well">
        <p class="f_legend">Data Perusahaan</p>
        <?php echo $this->form->lat; ?>
        <?php echo $this->form->lng; ?>
        <?php echo $this->form->name; ?>
        <?php echo $this->form->website; ?>
        <?php echo $this->form->address; ?>
        <?php echo $this->form->contact; ?>
        <?php echo $this->form->category; ?>
        <div class="form-actions">
          <?php echo $this->form->submit; ?>
        </div>
      </div>
    </div>
  </form>
</div>