<?php if ($this->pageCount > 1): ?>
  <div class="pagination pull-right">
    <ul>
      <li class="disabled">
        <a>
          Halaman
          <?php echo $this->current; ?>
          dari
          <?php echo $this->pageCount; ?>
        </a>
      </li>
      <?php if (isset($this->previous)): ?>
        <li>
          <a href="<?php echo $this->url(array('page' => $this->first)) . '#comment' ?>">
            <i class="icon-double-angle-left"></i>
          </a>
        </li>
        <li>
          <a href="<?php echo $this->url(array('page' => $this->previous)) . '#comment'; ?>">
            <i class="icon-angle-left"></i>
          </a>
        </li>
      <?php else: ?>
        <li class="disabled">
          <a>
            <i class="icon-double-angle-left"></i>
          </a>
        </li>
        <li class="disabled"><a><i class="icon-angle-left"></i></a></li>
      <?php endif; ?>

      <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
          <li><a href="<?php echo $this->url(array('page' => $page)) . '#comment'; ?>">
              <?php echo $page; ?></a>
          </li>
        <?php else: ?>
          <li class="active"><a><?php echo $page; ?></a></li>
        <?php endif; ?>
      <?php endforeach; ?>

      <?php if (isset($this->next)): ?>
        <li>
          <a href="<?php echo $this->url(array('page' => $this->next)) . '#comment'; ?>">
            <i class="icon-angle-right"></i>
          </a>
        </li>
        <li>
          <a href="<?php echo $this->url(array('page' => $this->last)) . '#comment' ?>">
            <i class="icon-double-angle-right"></i>
          </a>
        </li>
      <?php else: ?>
        <li class="disabled"><a><i class="icon-angle-right"></i></a></li>
        <li class="disabled">
          <a><i class="icon-double-angle-right"></i></a>
        </li>
      <?php endif; ?>
    </ul>
  </div>
<div class="clearfix"></div>
<?php endif; ?>