<?php $this->MinifyHeadLink()->appendStylesheet($this->baseUrl('lib/colorbox/colorbox.css')); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/colorbox/jquery.colorbox-min.js')); ?>
<?php $this->minifyHeadLink()->appendStylesheet($this->baseUrl('css/jcarousel-skin-mading.css')); ?>
<?php $this->minifyHeadScript()->appendFile($this->baseUrl('js/sidebar.js')); ?>

<div class="widget" style="padding: 0; border-radius: 5px;height: 600px;">
    <a class="twitter-timeline" width="100%" height="100%" href="https://twitter.com/smk4bdg" data-widget-id="309296562264215552">Tweets by @smk4bdg</a>
    <script>!function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (!d.getElementById(id)) {
                js = d.createElement(s);
                js.id = id;
                js.src = "//platform.twitter.com/widgets.js";
                fjs.parentNode.insertBefore(js, fjs);
            }
        }(document, "script", "twitter-wjs");</script>
    <style type="text/css">
        #twitter-widget-0 {
            width: 100%;
        }
    </style>
</div>

<div class = "agenda widget top-blue">
    <div class = "widget-header">
        <h4><i class = "icon-calendar"></i> <a href="<?php $this->url(array('controller'=>'events', 'action' => 'index')); ?>">Agenda</a></h4>
    </div>
    <div class = "widget-content">
        <ul class = "unstyled">
            <?php foreach ($this->Widget()->getUpcomingEvent() as $eventUC): ?>
                <li>
                    <div class="time">
                        <?php echo date("d M Y", strtotime($eventUC['from_date'])); ?> s/d <?php echo date("d M Y", strtotime($eventUC['from_date'])); ?>
                    </div>
                    <a href="#"><?php echo $eventUC['title']; ?></a>
                </li>
            <?php endforeach; ?>
            <?php foreach ($this->Widget()->getLatestEvent() as $eventL): ?>
                <li>
                    <del>
                        <div class="time">
                            <?php echo date("d M Y", strtotime($eventL['from_date'])); ?> s/d <?php echo date("d M Y", strtotime($eventL['from_date'])); ?>
                        </div>
                        <a href="#"><?php echo $eventL['title']; ?></a>
                    </del>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<div class="widget" style="padding: 0;text-align: center;">
    <ul id="mading" class="jcarousel-skin-mading">
        <?php foreach ($this->widget(false)->getActiveMading() as $index => $mading): ?>
            <li>
                <a href="<?php echo $this->baseUrl('upload/mading/' . $mading['image']); ?>"
                   class="mading"
                   title="<?php echo $mading['title']; ?>">
                       <?php
                       echo $this->timthumb($this->baseUrl('upload/mading/' . $mading['image']), 300, 400, 100);
                       ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<div class = "agenda widget top-red">
    <div class = "widget-header">
        <h4><i class = "icon-briefcase"></i> <a href="<?php $this->url(array('controller' => 'jobs', 'action' => 'index')); ?>">Lowongan Kerja</a></h4>
    </div>
    <div class = "widget-content">
        <ul class = "unstyled">
            <?php foreach ($this->Widget()->getLatestJobs() as $index => $job): ?>
                <li>
                    <a href="#"><?php echo $job['title']; ?></a><br />
                    <small>- <?php echo $job['company']; ?></small>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php if ($polling = $this->Widget(false)->getActivePolling()): ?>
    <?php
    $polls = Zend_Controller_Front::getInstance()->getRequest()->getCookie('polls');
    ?>
    <div class = "widget top-green" id="polling-widget">
        <div class = "widget-header">
            <h4><i class = "icon-list-alt"></i> Jajak Pendapat</h4>
        </div>
        <div class = "widget-content">
            <p><?php echo $polling[0]['question']; ?></p>
            <?php if ($polls): ?>
                <ul class="unstyled">
                    <?php foreach ($polling as $key => $result): ?>
                        <?php
                        $percent = strstr($result['percent'], '%', true);
                        if ($percent <= 10) $class = 'progress-danger';
                        elseif ($percent <= 20) $class = 'progress-warning';
                        elseif ($percent <= 30) $class = 'progress-info';
                        elseif ($percent > 40) $class = 'progress-success';
                        ?>
                        <li>
                            <?php echo $result['answer']; ?>
                            <span class="text-info pull-right">
                                <?php echo $result['total']; ?> Pemilih
                            </span>
                            <div class="progress <?php echo $class ?>">
                                <div class="bar"
                                     style="width: <?php echo $result['percent'] ?>">
                                         <?php echo round($result['percent']) . '%' ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <form action="<?php echo $this->url(array('controller' => 'polling', 'action'     => 'vote')); ?>" method = "post">
                    <input type="hidden"
                           name="question_id"
                           value="<?php echo $polling[0]['qid']; ?>" />
                    <input type="hidden"
                           name="return_uri"
                           value="<?php echo $this->url() ?>"/>
                    <ul class = "unstyled">
                        <?php foreach ($polling as $index => $polling): ?>
                            <li>
                                <label for="<?php echo 'vote' . $polling['aid']; ?>" class="radio">
                                    <input type = "radio"
                                           name = "vote"
                                           id="<?php echo 'vote' . $polling['aid'] ?>"
                                           value="<?php echo $polling['aid']; ?>" />
                                           <?php echo $polling['answer']; ?>
                                </label>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <input type = "submit" class = "btn btn-success pull-right" value = "Kirim" />
                    <div class = "clearfix"></div>
                </form>

            <?php endif; ?>

        </div>
        <div class = "widget-footer">

        </div>
    </div>

<?php endif; ?>
