<div class="row-fluid">
    <h3 class="heading">
        <small>Hasil pencarian untuk kata</small>
        <?php echo $this->q; ?>
        <div class="pull-right">
            <?php // echo $this->paginationControl($this->results, 'sliding', 'partial/search_pagination_control.phtml'); ?>
        </div>
    </h3>
</div>
<div class="row-fluid">
    <div class="span12">
        <ul class="unstyled">
            <?php foreach ($this->results as $index => $result): ?>
                <?php
                $editUrl = $this->url(array(
                    'controller' => $result->type,
                    'module'     => 'admin',
                    'action'     => 'edit',
                    'id'         => $result->id
                ));

                $deleteUrl = $this->url(array(
                    'controller' => $result->type,
                    'module'     => 'admin',
                    'action'     => 'delete',
                    'id'         => $result->id
                ));
                ?>
                <li>
                    <blockquote>
                        <span class="label label-info">
                            <?php echo $this->normalizeType($result->type); ?>
                        </span>
                        <a href="<?php echo $editUrl; ?>">
                            <?php echo $result->title; ?>
                        </a>
                        <small>
                            <?php echo $result->created_on; ?>
                            <a href="<?php echo $editUrl; ?>"><i class="icon-edit"></i></a>
                            <a href="<?php echo $deleteUrl; ?>"
                               onclick="return confirm('Apakah anda yakin?');">
                                <i class="icon-trash"></i>
                            </a>
                        </small>
                    </blockquote>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>