
<?php $this->headLink()->appendStylesheet($this->baseUrl('timeline-mading/css/styles.css')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('timeline-mading/framewarp/framewarp.css')); ?>
<?php echo $this->headLink(); ?>

<div class="container">
    <div class="span12">

        <div id="main">
            <img src="timeline-mading/img/tooltip.png" width="575" height="217" alt="FrameWarp Plugin"  />
            <a href="mading/frame.phtml" class="button2" id="b1">Try it!</a> <a href="message.html" class="button1" id="b2">Message Passing</a> <a href="#" class="button1" id="b3">With Cache</a> <a href="#" class="button1" id="b4">Without Cache</a>
            <p id="messages"></p>
        </div>
        
    </div>
</div>