<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/tiny_mce/tiny_mce.js'), 'text/javascript', array('minify_disabled' => true)); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('js/SITi_admin.js')); ?>
<?php $this->MinifyHeadScript()->appendScript("$(function(){SITi_tinyMCE.init();})") ?>
<form action="" method="post">
    <?php echo $this->form->title; ?>
    <div class="row-fluid">
        <div class="span8">
            <?php echo $this->form->content; ?>
        </div>
        <div class="span4">
            <div class="well">
                <?php echo $this->form->submit; ?>
                <?php echo $this->form->draft; ?>
            </div>
        </div>
    </div>
</form>