<?php echo $this->flashMessenger($this->messages); ?>
<form action="" method="post">
  <div class="row-fluid" style="margin-bottom: 20px">
    <div class="pull-left">
      <h3 style="display: inline">Berita</h3>
      <a href="<?php echo $this->url(array('action' => 'create')); ?>" 
         class="btn btn-link label label-success">Posting Berita</a>
    </div>
    <div class="pull-right">
      <?php
      echo $this->formSelect('filter[row]', $this->filter['row'], array(
          'style' => 'width: 50px'), array(
          5 => 5,
          10 => 10,
          15 => 15,
          25 => 25,
          50 => 50,
          100 => 100
      ));
      ?>
      <button class="btn" name="action" value="filter">Set</button>
    </div>
  </div>

  <div class="row-fluid">
    <div class="row-fluid">
      <div class="pull-left">
        <button class="btn btn-mini" name="action" value="delete"
                onclick="return confirm('Apakah anda yakin ingin menghapus berita yang dipilih?')">
          <i class="icon-trash"></i>
        </button>
        <button class="btn btn-mini" name="action" value="filter">
          <i class="icon-filter"></i> Gunakan Filter
        </button>
        <button class="btn btn-mini" name="action" value="reset">
          Atur Ulang Filter
        </button>
      </div>
      <div class="pull-right">
        <?php echo $this->paginationControl($this->news, 'sliding', 'partial/pagination_control.phtml'); ?>
      </div>
    </div>
    <div class="row-fluid">
      <table class="table table-striped table-condensed" id="news-table">
        <thead>
          <tr>
            <th><input type="checkbox" onclick="
              var checkboxes = $('#news-table tbody input:checkbox');
              if($(this).attr('checked')) {
                $(checkboxes).attr('checked', true);
              } else {
                $(checkboxes).removeAttr('checked');
              }"/>
            </th>
            <th>Judul</th>
            <th>Status</th>
            <th><i class="icon-eye-open"></i></th>
            <th></th>
          </tr>
          <!--filter-->
          <tr>
            <th></th>
            <th>
              <?php
              echo $this->formText('filter[title]', $this->filter['title'], array(
                  'placeholder' => 'Cari berdasarkan judul berita...'
              ));
              ?>
            </th>
            <th>
              <?php
              echo $this->formSelect('filter[status]', $this->filter['status'], array(), array(
                  null => '--Tampilkan semua status.',
                  Admin_Model_Status::ARCHIVED => "Diarsipkan ({$this->countStatus['archived']})",
                  Admin_Model_Status::DRAFT => "Draft ({$this->countStatus['draft']})",
                  Admin_Model_Status::PENDING => "Menunggu Persetujuan ({$this->countStatus['pending']})",
                  Admin_Model_Status::PUBLISH => "Diterbitkan ({$this->countStatus['publish']})"
              ));
              ?>
            </th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->news as $index => $news): ?>
            <tr>
              <td>
                <input type="checkbox" name="news[]" id="" 
                       value="<?php echo $news->id; ?>" />
              </td>
              <td>
                <a href="">
                  <strong><?php echo $news->title; ?></strong>
                </a>
              </td>
              <td><?php echo $this->status($news->status); ?></td>
              <td>
                <span class="badge badge-info">
                  <?php echo $news->views; ?>
                </span>
              </td>
              <td>
                <?php if (Admin_Model_Status::ARCHIVED === $news->status): ?>
                  <a href="<?php echo $this->url(array('action' => 'restore', 'id' => $news->id)); ?>"
                     title="Kembalikan">
                    <i class="icon-refresh"></i>
                  </a>
                <?php endif; ?>
                <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $news->id)); ?>"
                   title="Sunting">
                  <i class="icon-edit"></i></a>
                <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $news->id)); ?>"
                   onclick="return confirm('Apakah anda yakin ingin menghapus berita ini?')">
                  <i class="icon-trash"></i></a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</form>

