<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php echo $this->headTitle('SMKN 4 Bandung - Admin'); ?>

        <?php
        $user = Zend_Auth::getInstance()->getIdentity();

        $this->MinifyHeadLink()
        ->prependStylesheet($this->baseUrl('lib/bootstrap/css/bootstrap.css'))
        ->appendStylesheet($this->baseUrl('lib/bootstrap/css/bootstrap-responsive.css'))
        ->appendStylesheet($this->baseUrl('lib/jquery/qtip2/jquery.qtip.min.css'))
        ->prependStylesheet($this->baseUrl('lib/Tag-Handler/css/jquery.taghandler.css'))
        ->appendStylesheet($this->baseUrl('lib/jquery-ui/css/Aristo/Aristo.css'))
        ->appendStylesheet($this->baseUrl('lib/gebo/css/blue.css'))
        ->appendStylesheet($this->baseUrl('lib/gebo/css/style.css'))
//        ->appendStylesheet('http://fonts.googleapis.com/css?family=PT+Sans')
        ->appendStylesheet($this->baseUrl('lib/font-awesome/css/font-awesome.css'));

        $this
        ->MinifyHeadScript()
        ->prependFile($this->baseUrl('lib/jquery/jquery-1.8.3.js'))
        ->appendFile($this->baseUrl('lib/bootstrap/js/bootstrap.js'))
        ->appendFile($this->baseUrl('lib/bootstrap/js/bootstrap.plugins.js'), 'text/javascript', array('minify_disabled' => true))
        ->appendFile($this->baseUrl('lib/jquery/jquery.debouncedresize.min.js'))
        ->appendFile($this->baseUrl('lib/jquery/jquery.actual.min.js'))
        ->appendFile($this->baseUrl('lib/jquery/cookie.js'))
        ->appendFile($this->baseUrl('lib/jquery/qtip2/jquery.qtip.min.js'))
        ->appendFile($this->baseUrl('lib/jquery/antiscroll/antiscroll.js'))
        ->appendFile($this->baseUrl('lib/jquery/antiscroll/jquery-mousewheel.js'))
        ->appendFile($this->baseUrl('lib/other/ios-orientationchange-fix.js'))
        ->appendFile($this->baseUrl('lib/gebo/js/gebo_common.js'));
        ?>

        <?php echo $this->MinifyHeadLink(); ?>
        <?php echo $this->MinifyHeadScript(); ?>

        <?php
        $config = new Zend_Config_Xml(APPLICATION_PATH . '/configs/navigation.xml', 'admin');
        $navigation = new Zend_Navigation($config);
        $this->navigation($navigation)
        ->setAcl(new SITi_Acl())->setRole($user->role)
        ;

        $article = new Admin_Model_DbTable_Article();
        $count = $article->select()
        ->from('article', array('COUNT(*)'))
        ->where('status = ?', Admin_Model_Status::PENDING);
        $count = $article->getAdapter()->fetchOne($count);

        $menu = $this->navigation()->myMenu()->setUlClass('nav nav-list');
        $menu = preg_replace('#\{(.*)\}#', '<i class="$1"></i>', $menu);
        $menu = str_replace(':articleCount', $count, $menu);
        ?>


        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-38322604-1']);
            _gaq.push(['_trackPageview']);
            _gaq.push(['_setDomainName', 'none']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

        </script>

        <link rel="shortcut icon" href="/img/favico.png" />

        <style type="text/css">
            form select, select {
                margin-bottom: 0;
            }
            .table thead th {
                vertical-align: middle;
            }
            .table thead input {
                margin-bottom: 0;
            }
        </style>

        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/ie.css" />
            <script src="js/ie/html5.js"></script>
            <script src="js/ie/respond.min.js"></script>
        <![endif]-->

        <script>
            //* hide all elements & show preloader
            document.documentElement.className += 'js';
        </script>
    </head>
    <body>
        <div id="loading_layer" style="display:none"><img src="/img/ajax_loader.gif" alt="" /></div>
        <div id="maincontainer" class="clearfix">
            <!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="<?php echo $this->url(array('controller' => 'index', 'action'     => 'index')); ?>">
                              <!--<i class="icon-home icon-white"></i>-->
                                <img src="/img/favico.png" width="32" alt="" />
                                Teknik Informatika
                            </a>
                            <ul class="nav user_menu pull-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <?php echo $this->thumbnail('avatar', Zend_Auth::getInstance()->getIdentity()->avatar, 'no-avatar.jpg', 20, 20, 100, null); ?>
                                        <?php if (null == Zend_Auth::getInstance()->getIdentity()->fullname): ?>
                                            <?php echo Zend_Auth::getInstance()->getIdentity()->username; ?>
                                        <?php else: ?>
                                            <?php echo Zend_Auth::getInstance()->getIdentity()->fullname; ?>
                                        <?php endif; ?>
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="<?php echo $this->url(array('module'     => 'default', 'controller' => 'index', 'action'     => 'index')); ?>">
                                                <i class="icon-home"></i> Ke halaman depan
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url(array('controller' => 'user', 'action'     => 'index')); ?>">
                                                <i class="icon-user"></i> Profil
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url(array('controller' => 'user', 'action'     => 'setting')); ?>">
                                                <i class="icon-cog"></i> Sunting Akun
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url(array('controller' => 'user', 'action'     => 'logout')); ?>">
                                                <i class="icon-off"></i> Keluar
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <!--                            <a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
                                                            <span class="icon-align-justify icon-white"></span>
                                                        </a>
                                                        <nav>
                                                            <div class="nav-collapse">
                                                            </div>
                                                        </nav>-->
                        </div>
                    </div>
                </div>
            </header>

            <!-- main content -->
            <div id="contentwrapper">
                <div class="main_content">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>

            <!-- sidebar -->
            <a href="javascript:void(0)" class="sidebar_switch on_switch ttip_r" title="Hide Sidebar">Sidebar switch</a>
            <div class="sidebar">
                <div class="antiScroll">
                    <div class="antiscroll-inner">
                        <div class="antiscroll-content">
                            <div class="sidebar_inner">
                                <form action="<?php echo $this->url(array('controller' => 'search', 'module'     => 'admin'), null, true); ?>"
                                      class="input-append" method="get"
                                      onsubmit="return this.query.value !== ''">
                                    <input autocomplete="off" name="query" class="search_query input-medium" size="16" type="text" placeholder="Pencarian..." /><button type="submit" class="btn"><i class="icon-search"></i></button>
                                </form>
                                <div id="side_accordion" class="accordion">
                                    <?php echo $menu; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script>
            $(document).ready(function() {
                //* show all elements & remove preloader
                setTimeout('$("html").removeClass("js")', 1000);
            });
            </script>

        </div>
    </body>
</html>