<!DOCTYPE HTML>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
     <?php $this->headLink()->appendStylesheet($this->baseUrl('lib/bootstrap/css/bootstrap.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('lib/bootstrap/css/bootstrap-responsive.css')); ?>
    <?php $this->headScript()->prependFile($this->baseUrl('lib/jquery/jquery-1.8.3.js')); ?>

    <?php $this->headScript()->appendFile($this->baseUrl('lib/bootstrap/js/bootstrap.js')); ?>
    
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    
    <title></title>
  </head>
  <body>
    <?php echo $this->layout()->content; ?>
  </body>
</html>