
<div class="row-fluid">



    <div class="span8">
        <div class="content-inner">
            <div class="pull-left">
                <span class="label label-info" style="font-size: 30px; line-height: 47px; padding: 3px 11px; margin-top: -13px;">Agenda</span>
            </div>
            
            <br />
            <br />
            <br />
            <br />
            
            
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            Kegiatan
                        </th>
                        <th>
                            Lokasi
                        </th>
                        <th colspan="3" style="text-align: center" width="200px">
                            Waktu
                        </th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach ($this->events as $index => $event): ?>
                        <?php
                        
                        

                        
                        if (strtotime($event['until_date']) < time()) {
                            $extra = "error";
                        } elseif (strtotime($event['until_date']) > time()) {
                            $extra = "success";
                        } else{
                            $extra = "success";
                        }
                        ?>
                        <tr class="<?php echo $extra; ?>">
                            <?php
                            $link = $this->url(array('controller' => 'event', 'action' => 'view', 'id' => $event['id']))
                            ?>
                            <td>
                                <a class="userlink" href = '<?php echo $link ?>' data-toggle='modal'><?php echo $event['title']; ?></a>
                            </td>
                            <td>
                                <?php echo $event['location']; ?>
                            </td>
                            <td>
                                <?php echo date("j M y", strtotime($event['from_date'])); ?>
                            </td>
                            <td>
                                -
                            </td>
                            <td>
                                <?php echo date("j M y", strtotime($event['until_date'])); ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->events, 'sliding', 'pagination_control.phtml'); ?>
        </div>
    </div>
    <div class="span4 well sidebar">
        <div class="widget top-blue">
            <div class="widget-header">
                <h4>Tag</h4>
            </div>
            <div class="widget-content">
                <?php echo $this->widget()->getTagCloud(); ?>
            </div>
        </div>
        <?php echo $this->render('sidebar.phtml'); ?>
    </div>

</div>