<div class="main row-fluid">
  <ul class="nav nav-tabs fixed-bottom" id="profil-tabs">
    <li class="active">
      <a href="#1A" data-toggle="tab">Pimpinan</a>
    </li>
    <li class="">
      <a href="#1B" data-toggle="tab">Visi Misi</a>
    </li>
    <li class="">
      <a href="#1C" data-toggle="tab">Sejarah</a>
    </li>
    <li class="">
      <a href="#1D" data-toggle="tab">Motto</a>
    </li>
  </ul>
  <div class="span8">





        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="1A">
                <div class="hero-unit">
                    <h1>
                        Pimpinan
                    </h1>
                </div>

                <center>
                    <div class="row-fluid">

                        <div class="span12 well">
                            <u><h3>Kepala Sekolah</h3></u>
                            <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>

                            <br />
                            <p>
                                <b>Drs. Asep Dada Wahyudin, MMPd</b>
                            </p>

                        </div>


                        <br />
                        <hr />

                        <div class="row-fluid">
                            <div class="span6">
                                <br />
                                <h4>Wakasek Mutu Manajemen</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Drs. Dedy Sukmayadi
                                </p>
                            </div>

                            <div class="span6">
                                <br />
                                <h4>Wakasek Umum</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Drs. Enjang Sarifudin
                                </p>
                            </div>



                        </div>

                        <br />
                        <hr />

                        <div class="row-fluid">

                            <div class="span6">
                                <br />
                                <h4>Wakasek Lit Bang</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Drs. Eman S.H., MMPd
                                </p>


                            </div>

                            <div class="span6">
                                <br />
                                <h4>Wakasek Kurikulum</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Agus M, S.Pd MT
                                </p>
                            </div>


                        </div>

                        <br />
                        <hr />

                        <div class="row-fluid">
                            <div class="span6">
                                <br />
                                <h4>Wakasek Kesiswaan</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Drs. Sriyanta
                                </p>

                            </div>
                            <div class="span6">
                                <br />
                                <h4>Wakasek Hubin</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Teguh Iswahyudi, S.Pd
                                </p>
                            </div>
                        </div>

                        <br />
                        <hr />

                        <div class="row-fluid">
                            <div class="span6">
                                <br />
                                <h4>Wakasek Sapras</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Drs. Nana Kamaen
                                </p>

                            </div>
                            <div class="span6">
                                <br />
                                <h4>Kasubag TU</h4>
                                <img data-src="holder.js/140x140" alt="Kepala Sekolah" class="img-rounded" style="width: 140px; height: 140px;" src="img/imgFolder/img-rounded.png"/>
                                <p>
                                    Saepudin
                                </p>
                            </div>
                        </div>

                        <br />
                        <hr />



                    </div>



                </center>



            </div>
            <div class="tab-pane fade" id="1B">
                <div class="hero-unit">
                    <h1>
                        Visi Misi
                    </h1>

                </div>

                <div class="row-fluid">
                    <div class="span12 well well-large">
                        <div class="jumbotron">
                            <blockquote>
                                <h3>Menjadi Sekolah Menengah Kejuruan Unggulan di Jawa Barat yang berstandar Nasional dan Internasional.</h3>
                            </blockquote>
                        </div>


                        <div class="row-fluid well-large">
                            <div class="span6">
                                <br />
                                Memperoleh calon siswa melalui seleksi yang proporsional.
                            </div>

                            <div class="span6">
                                <br />
                                Mendidik, mengembangkan karakter dan bakat peserta didik melalui Program Mata Pelajaran Wajib,Kejuruan, Muatan Lokal serta Pengembangan diri.
                            </div>
                        </div>

                        <br />
                        <hr />

                        <div class="row-fluid well-large">
                            <div class="span6">
                                <br />
                                Membangun Kepercayaan Masyarakat melalui keterbukaan manajemen dan keuangan sekolah.
                            </div>


                            <div class="span6">
                                <br />
                                Membangun kredibilitas dan akuntabilitas sekolah melalui administrasi yang tertib, bersih dan transparan.

                            </div>
                        </div>

                        <br />
                        <hr />

                        <div class="row-fluid well-large">
                            <div class="span6">
                                <br />
                                Meningkatkan kepercayaan stakeholder melalui Program kejuruan dan kualitas kegiatan belajar mengajar.
                            </div>



                            <div class="span6">
                                <br />
                                Mengembangkan infrastruktur untuk mendukung proses kegiatan belajar mengajar dengan bantuan stakeholder.

                            </div>
                        </div>

                        <br />
                        <hr />

                        <div class="row-fluid well-large">
                            <div class="span6">
                                Menghasilkan lulusan yang mampu bersaing dimasyarakat serta tidak melupakan budaya Jawa Barat.
                            </div>

                        </div>


                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="1C">
                <div class="hero-unit">
                    <h1>
                        Sejarah
                    </h1>
                </div>

                <div class="row-fluid">
                    <div class="span12 well">

                        <p>
                            Sesuai tuntutan pasar kerja pada tahun pelajaran SMK Negeri 4 Bandung bermula dari STM Negeri 2 yang berdiri pada tahun 1962, dengan jurusan Mesin, Bangunan, Listrik dan Kimia dengan lokasi di Jl. Ciliwung Bandung.
                        </p>

                        <p>
                            Pada tahun 1965 sekolah berpindah ke Jl. Kelenteng dan selanjutnya pada tahun 1969 sekolah berpindah ke Jl. Kliningan No. 6 Buahbatu Bandung sampai sekarang. Jurusan menjadi Listrik Instalasi, dan Elektronika Komunikasi.
                        </p>

                        <p>
                            Pada tahun pelajaran 1999/2000 STM Negeri 2 Bandung berubah nama menjadi SMK Negeri 4 Bandung. Program keahlian yang dibuka menjadi :
                        </p>

                        <ul>
                            <li>
                                Teknik Elektronika Komunikasi


                            </li>
                            <li>
                                Teknik Listrik Pemakaian

                            </li>
                            <li>

                                Teknik Instalasi Listrik

                            </li>
                            <li>

                                Teknik Informatika dan Komunikasi
                            </li>

                        </ul>

                        <p>
                            Pada tahun 2004 SMK Negeri 4 Bandung membuka Program Keahlian tersebut di atas menjadi :
                        </p>

                        <ul>
                            <li>Teknik Audio Video</li>

                            <li>Teknik Pemanfaatan Tenaga Liatrik</li>

                            <li>Teknik Komputer dan Jaringan</li>

                            <li>Rekayasa Perangkat Lunak</li>
                        </ul>

                        <p>
                            Pada tahun 2009 SMK Negeri 4 Bandung membuka program keahlian baru hingga memiliki 6 program keahlian, yaitu:
                        </p>

                        <ul>
                            <li>Teknik Elektronika Audio Video</li>

                            <li>Teknik Pemanfaaan Tenaga Listrik</li>

                            <li>Teknik Otomasi Industri</li>

                            <li>Teknik Komputer Jaringan</li>

                            <li>Rekayasa Perangkat Lunak</li>

                            <li>Multimedia</li>
                        </ul>

                    </div>

                </div>
            </div>
            <div class="tab-pane fade" id="1D">
                <div class="hero-unit">
                    <h1>
                        Motto
                    </h1>
                </div>
            </div>
            <div class="tab-pane fade" id="1E">
                <div class="hero-unit">
                    <h1>
                        Data Sekolah
                    </h1>
                </div>
                <div class="row-fluid">
                        <div class="span12 well-large">
                            <table class="table table-hover">
                                <tbody>
                                    <tr>
                                        <td>
                                            Nama Sekolah
                                        </td>
                                        <td>
                                            : SMKN 4 BANDUNG
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            NSS
                                        </td>
                                        <td>
                                            : 321026006001
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            NPSN
                                        </td>
                                        <td>
                                            : 20219144
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            SK Pendirian
                                        </td>
                                        <td>
                                            : 5/Djapt/-1/62
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Tgl. SK Pendirian
                                        </td>
                                        <td>
                                            : 5 Februari 1962
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Alamat
                                        </td>
                                        <td>
                                            : Jalan Kliningan No.6 RT 02 RW 05 Buah Batu 42064 Kecamatan lengkong Kelurahan Turangga Kota Ba
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            No. Telp/Fax
                                        </td>
                                        <td>
                                            : 022 - 7303736
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Website/Email
                                        </td>
                                        <td>
                                            : www.smkn4bandung.sch.id / info@smkn4bandung.sch.id
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Jumlah Guru
                                        </td>
                                        <td>
                                            : PNS : 51 Orang, NonPNS : 46 Orang
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Jumlah Karyawan
                                        </td>
                                        <td>
                                            : PNS: 5 Orang, NonPNS: 28 Orang
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Luas Tanah
                                        </td>
                                        <td>
                                            : 13364 m2
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="120px">
                                            Luas Bangunan
                                        </td>
                                        <td>
                                            : 3816 m2
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <div class=" sidebar span4 well">
        <?php
        echo $this->render('sidebar.phtml');
        ?>
    </div>
</div>
