<?php $this->minifyHeadlink()->appendStylesheet($this->baseUrl('css/application/search.css')); ?>
<div class="main row-fluid">
    <div class="span8">
        <div class="content-inner">
            <h4>Hasil pencarian artikel dengan kata kunci #<?php echo $this->keyword; ?></h4>
            <ul class="unstyled media-list search-result article">
                <?php foreach ($this->articles as $index => $article): ?>
                    <?php
                    $url = $this->url(array(
                        'module'     => 'default',
                        'controller' => 'article',
                        'action'     => 'view',
                        'id'         => $article['id']
                    ), null, true);
                    ?>
                    <li class="media">
                        <div class="date media-object pull-left" style="margin-top: 0">
                            <span class="day"><?php echo Date('d', strtotime($article['created_on'])); ?></span>
                            <span class="month"><?php echo Date('M', strtotime($article['created_on'])); ?></span>
                        </div>
                        <div class="media-body">
                            <blockquote>
                                <h4 class="media-heading">
                                    <a href="<?php echo $url; ?>">
                                        <?php echo $article['title']; ?>
                                    </a>
                                </h4>
                                <?php echo strip_tags($this->truncate($article['content'], 250)); ?>
                                <small style="margin-top: 10px;
                                       ">
                                    <i class="icon-user"></i><cite><a href="#"><?php echo $article['created_by']; ?></a></cite></a>&nbsp;&nbsp;
                                    <i class="icon-eye-open"></i>&nbsp;<?php echo $article['views']; ?>&nbsp;&nbsp;
                                    <i class="icon-comments"></i>&nbsp;<?php echo $article['comments']; ?> &nbsp;&nbsp;
                                    <i class="icon-thumbs-up"></i>&nbsp;
                                    <?php echo (null != $article['likes']) ? count(explode(',', $article['likes'])) : 0; ?> &nbsp;&nbsp;
                                    <i class="icon-tags"></i>&nbsp;<?php echo $this->tags($article['tags']); ?>
                                </small>
                            </blockquote>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="span4 well sidebar">
        <?php echo $this->render('sidebar.phtml'); ?>
    </div>
</div>
