<?php $this->headLink()->appendStylesheet($this->baseUrl('lib/datepicker/datepicker.css')); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/datepicker/bootstrap-datepicker.js')); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('js/SITi_admin.js')); ?>

<?php
$this->MinifyHeadScript()->appendScript(
        <<<SCRIPT
 $(function(){
   SITi_datepicker.init();
 });
SCRIPT
);
?>

<?php echo $this->flashMessenger($this->messages); ?>

<form action="" method="post">
  <div class="row-fluid" style="margin-bottom: 20px">
    <div class="pull-left">
      <h3 style="display: inline">Kegiatan</h3>
      <a class="btn btn-link label label-success"
         href="<?php echo $this->url(array('action' => 'create')); ?>">
        Tambah Kegiatan
      </a>
    </div>
    <div class="pull-right">
      <?php
      echo $this->formSelect('filter[row]', $this->filter['row'], array('style' => 'width:55px'), array(
          5 => 5,
          10 => 10,
          15 => 15,
          25 => 25,
          50 => 50,
          100 => 100
      ));
      ?>
    </div>
  </div>
  <div class="row-fluid">
    <div class="row-fluid">
      <div class="pull-left">
        <button name="action" value="filter" style="position: absolute;visibility: hidden" ></button>
        <button class="btn btn-mini btn-danger"
                name="action"
                value="delete"
                title="Hapus kegiatan yang dipilih"
                onclick="return confirm('Apakah anda yakin ingin menghapus kegiatan yang dipilih?')">
          <i class="icon-trash"></i>
        </button>
        <button class="btn btn-mini"
                name="action"
                value="filter"
                title="Gunakan Filter">
          <i class="icon-filter"></i> Gunakan Filter
        </button>
        <button class="btn btn-mini"
                name="action"
                value="reset"
                title="Atur Ulang Filter">
          Atur Ulang Filter
        </button>
      </div>
      <div class="pull-right">
        <?php echo $this->paginationControl($this->events, 'sliding', 'partial/pagination_control.phtml'); ?>
      </div>
    </div>
    <div class="row-fluid">
      <table class="table table-striped table-condensed" id="event-table">
        <thead>
          <tr>
            <th>
              <input type="checkbox" onclick="
                var checkboxes = $('#event-table tbody input:checkbox');
                if($(this).attr('checked')) {
                  $(checkboxes).attr('checked', true);
                }else {
                  $(checkboxes).removeAttr('checked');
                }
                     "/>
            </th>
            <th>Kegiatan</th>
            <th>Status</th>
            <th>Lokasi</th>
            <th>Waktu</th>
            <th><i class="icon-eye-open"></i></th>
            <th></th>
          </tr>
          <!--filter-->
          <tr>
            <th></th>
            <th>
              <?php
              echo $this->formText('filter[title]', $this->filter['title'], array(
                  'placeholder' => 'Cari berdasarkan nama kegiatan...'));
              ?>
            </th>
            <th>
              <?php
              echo $this->formSelect('filter[status]', $this->filter['status'], array(), array(
                  null => '--Tampilkan semua status.',
                  Admin_Model_Status::ARCHIVED => "Diarsipkan ({$this->countStatus['archived']})",
                  Admin_Model_Status::DRAFT => "Draft ({$this->countStatus['draft']})",
                  Admin_Model_Status::PENDING => "Menunggu Persetujuan ({$this->countStatus['pending']})",
                  Admin_Model_Status::PUBLISH => "Diterbitkan ({$this->countStatus['publish']})"
              ));
              ?>
            </th>

            <th>
              <?php
              echo $this->formText('filter[location]', $this->filter['location'], array(
                  'placeholder' => 'Cari berdasarkan lokasi kegiatan...'));
              ?>
            </th>
            <th>
              <?php
              $datepicker = new SITi_Form_Decorator_Datepicker();
              $datepicker->setOption('id', 'dp_start');
              echo $datepicker->render($this->formText('filter[from_date]', $this->filter['from_date'], array('class' => 'span8')));
              ?>
            </th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->events as $index => $event): ?>
            <tr>
              <td>
                <input type="checkbox" name="events[]" 
                       value="<?php echo $event->id; ?>" />
              </td>
              <td>
                <a href="#">
                  <strong><?php echo $event->title; ?></strong>
                </a>
              </td>
              <td>
                <?php echo $this->status($event->status); ?>
              </td>
              <td><?php echo $event->location; ?></td>
              <td>
                <?php echo date('d/m/Y', strtotime($event->from_date)); ?> -
                <?php echo date('d/m/Y', strtotime($event->until_date)) ; ?>
              </td>

              <td>
                <span class="badge badge-info"><?php echo $event->views; ?></span>
              </td>
              <td>
                <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $event->id)); ?>"
                   title="Sunting">
                  <i class="icon-edit"></i>
                </a>
                <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $event->id)); ?>"
                   title="Hapus"
                   onclick="return confirm('Apakan anda yakin ingin menghapus kegiatan ini?')">
                  <i class="icon-trash"></i>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</form>