<?php $this->MinifyHeadLink()->appendStylesheet($this->baseUrl('css/application/gallery.css')); ?>
<div class="main row-fluid">
    <div class="span12">
        <div class="content-inner">
            <ul class="thumbnails gallery-grid">
                <?php foreach ($this->albums as $index => $album): ?>
                    <li>
                        <a href="<?php echo $this->url(array('action' => 'view', 'id'     => $album['id'])); ?>">
                            <figure>
                                <div>
                                    <?php if (isset($album['photos'][0])): ?>
                                        <?php echo $this->timthumb($album['photos'][0], 230, 150, 100); ?>
                                    <?php else: ?>
                                        <img src="http://www.placehold.it/250x180/FFFFFF/AAAAAA&text=Tidak+ada+foto" alt="" />
                                    <?php endif; ?>
                                </div>
                                <figcaption>
                                    <h5><?php echo $album['title']; ?></h5>
                                    <small style="font-size: 11px">
                                        <i class="icon-calendar"></i>&nbsp;<?php echo Date('d F Y', strtotime($album['date'])); ?>&nbsp;&nbsp;
                                        <i class="icon-picture"></i>&nbsp;<?php echo count($album['photos']); ?> Foto
                                    </small>

                                </figcaption>
                            </figure>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12 well bottombar">
        <?php echo $this->render('bottombar.phtml'); ?>
    </div>
</div>
