<?php
$this->MinifyHeadLink()->appendStylesheet($this->baseUrl('lib/colorbox/colorbox.css'));
$this->MinifyHeadScript()
->appendFile($this->baseUrl('lib/colorbox/jquery.colorbox-min.js'))
->appendFile($this->baseUrl('js/application/gallery.js'));
?>
<div class="main row-fluid">
    <div class="span12">
        <div class="content-inner">
            <h4>Galeri #<?php echo $this->album['title']; ?></h4>
            <ul class="thumbnails" style="margin-top: 40px">
                <?php foreach ($this->album['photos'] as $index => $photo): ?>
                    <li class="thumbnail">
                        <a href="<?php echo $photo['src']; ?>" class="colorbox">
                            <?php echo $this->timthumb($photo['src'], 150, 150, 100); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12 well bottombar">
        <?php echo $this->render('bottombar.phtml'); ?>
    </div>
</div>