<?php $this->headScript()->appendFile($this->baseUrl('lib/jquery-ui/jquery-ui-1.8.23.custom.min.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/highlight/index.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/highlight/index.css')); ?>
<?php echo $this->FlashMessenger($this->messages); ?>
<div class="row-fluid">
  <h3 style="display: inline">Highlight</h3>
  <a href="<?php echo $this->url(array('action' => 'create')); ?>"
     class="btn btn-link label label-success">
    Tambah Baru
  </a>
</div>
<div class="row-fluid">
  <ul id="highlight-images" class="ui-sortable unstyled">
    <?php foreach ($this->paginator as $index => $highlight): ?>
      <li id="<?php echo 'images_' . $highlight['id'] ?>" class="well">
        <div class="pull-left">
          <div class="handle"></div>
          <?php
          echo $this->thumbnail('highlight', $highlight['image']
                  , 'default.png', 300, 100, 100, '');
          ?></div>
        <div class="detail">
          <table>
            <tr>
              <th>Judul</th>
              <td>:&nbsp;<strong><?php echo $highlight['title']; ?></strong></td>
            </tr>
            <tr>
              <th>Link</th>
              <td>:&nbsp;<a href="<?php echo $highlight['link']; ?>" target="_blank"><?php echo $highlight['link']; ?></a></td>
            </tr>
            <tr>
              <th>Dibuat Pada</th>
              <td>:&nbsp;<?php echo Date('d/m/Y', strtotime($highlight['created_on'])); ?></td>
            </tr>
            <tr>
              <th>Oleh</th>
              <td>:&nbsp;<?php echo $highlight['created_by']; ?></td>
            </tr>
          </table>
        </div>
        <div class="dropdown controls">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">
            <i class="caret"></i>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $highlight['id'])); ?>">
                <i class="icon-edit"></i>&nbsp;Sunting</a>
            </li>
            <li><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $highlight['id'])); ?>"
                   onclick="return confirm('Apakah anda yakin ingin menghapus highlight ini?')">
                <i class="icon-trash"></i>&nbsp;Hapus</a>
            </li>
          </ul>
        </div>
        <div class="clearfix"></div>
      </li>
    <?php endforeach; ?>
  </ul>
</div>