<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/jquery-ui/jquery-ui-1.8.23.custom.min.js')); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/jCarousel/lib/jquery.jcarousel.min.js')); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('js/mading/index.js')); ?>
<?php $this->MinifyHeadLink()->appendStylesheet($this->baseUrl('css/mading/index.css')); ?>
<?php echo $this->flashMessenger($this->messages); ?>

<div class="row-fluid">
    <div class="pull-left">
        <h3 style="display: inline">Majalah Dinding</h3>
        <a href="<?php echo $this->url(array('action' => 'create')); ?>"
           class="btn btn-link label label-success">
            Tambah Mading
        </a>
    </div>
    <div class="pull-right">
        <img id="ajax-process" src="/img/ajax_loader.gif" style="display: none;" alt="" />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">

        <ul class="jcarousel-skin-tango thumbnails" id='mading'>
            <?php foreach ($this->mading as $index => $mading): ?>
                <?php
                $updateUrl = $this->url(array(
                    'controller' => 'mading',
                    'module'     => 'admin',
                    'action'     => 'edit',
                    'id'         => $mading['id']
                ));
                ?>
                <li id="<?php echo 'mading_' . $mading['id']; ?>">
                    <div class="well well-small">
                        <div class="handle">
                            <strong title="<?php echo $mading['title']; ?>">
                                <?php echo $this->truncate($mading['title'], 30); ?>
                            </strong>
                        </div>
                        <figure>
                            <?php
                            echo $this->timthumb($this->baseUrl('upload/mading/' . $mading['image']), 400, 600, 100, array());
                            ?>
                            <figcaption>
                                Dibuat oleh <a href="#"><?php echo $mading['created_by']; ?></a>
                                <br />
                                <?php echo Date('d F Y', strtotime($mading['created_on'])); ?>
                                <div class="pull-right">
                                    <a href="<?php echo $updateUrl; ?>" title="Sunting">
                                        <i class="icon-edit"></i>
                                    </a>
                                    <a href="javascript:void(0)" title="Hapus" class="remove-mading"
                                       data-remove-id="<?php echo $mading['id']; ?>">
                                        <i class="icon-remove"></i>
                                    </a>
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>