<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/jquery-ui/jquery-ui-1.8.23.custom.min.js')); ?>
<?php $this->MinifyHeadScript()->appendFile($this->baseUrl('lib/jCarousel/lib/jquery.jcarousel.min.js')); ?>

<link rel="stylesheet" href="/css/mading/index.css" type="text/css" />

<div class="row-fluid">
    <h3 style="display: inline">Majalah Dinding</h3>
    <a href="<?php echo $this->url(array('action' => 'create')); ?>"
       class="btn btn-link label label-success">
        Tambah Mading
    </a>
</div>
<div class="row-fluid">
    <div class="span12">
        <ul class="jcarousel-skin-tango thumbnails" id='mading'>
            <?php foreach ($this->mading as $index => $mading): ?>
                <li id="<?php echo 'mading_' . $mading['id']; ?>">
                    <div class="well well-small">
                        <div class="handle">
                            <strong><?php echo $mading['title']; ?></strong>
                        </div>
                        <figure>
                            <?php
                            echo $this->timthumb($this->baseUrl('upload/mading/' . $mading['image']), 400, 600, 100, array());
                            ?>
                            <figcaption>
                                Dibuat oleh <a href="#"><?php echo $mading['created_by']; ?></a>
                                <br />
                                <?php echo Date('d F Y', strtotime($mading['created_on'])); ?>
                            </figcaption>
                        </figure>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        $("#mading").sortable({
            handle: '.handle',
            placeholder: 'sortable-placeholder',
            forcePlaceholderSize: true,
            animation: {
                duration: 800,
                easing: 'linear'
            },
            update: function(event, ui) {
                var order = $("#mading").sortable('serialize');
                $.ajax({
                    url: '/admin/mading/order',
                    type: 'post',
                    data: order,
                    cache: false,
                });
            }
        });

        $('#mading').jcarousel({
            scroll: 1,
            visible: 4
        });
    })
</script>
